allowBuilds:
  '@vitejs/vite-plugin-react-monorepo@https://codeload.github.com/vitejs/vite-plugin-react/tar.gz/1609186b9f379d4c1cf75c60e878d8b4f7675ab3': set this to true or false
  esbuild: set this to true or false
